[Variables]

; カラーの定義です。
Background = 000000C0
Foreground = F0FFFFFF
Frame = 8BB725FF
Frame2 = 00000000

; 書式設定の定義です。
[FontDriveLetter]
FontSize = 16
StringStyle = Normal
StringAlign = Center
FontFace = Segoe UI
FontColor = #Foreground#
StringEffect = Shadow
FontEffectColor = 646464FF
AntiAlias = 1

[FontVal]
FontSize = 10
StringStyle = Normal
StringAlign = Right
FontFace = Segoe UI
FontColor = #Foreground#
StringEffect = Shadow
FontEffectColor = 646464FF
AntiAlias = 1

[FontLabel]
FontSize = 8
StringStyle = Normal
StringAlign = Left
FontFace = Segoe UI
FontColor = #Foreground#
StringEffect = Shadow
FontEffectColor = 646464FF
AntiAlias = 1
