[Variables]

; カラーの定義です。
Background = 000000C0
Foreground = F0FFFFFF
Separator = F0FFFFA0
Frame = 32A69CFF
Frame2 = 00000000

; 書式設定の定義です。
[FontTitle]
FontSize = 10
StringStyle = Normal
StringAlign = Center
FontFace = Segoe UI
FontColor = #Foreground#
StringEffect = Shadow
FontEffectColor = 646464FF
AntiAlias = 1
ClipString = 1

[FontContent]
FontSize = 8
StringStyle = Normal
StringAlign = Left
FontFace = Segoe UI
FontColor = #Foreground#
StringEffect = Shadow
FontEffectColor = 646464FF
AntiAlias = 1
ClipString = 1