[Variables]
; カラーの定義です。
Background = 000000C0
Foreground = F0FFFFFF
Frame = 2496FFFF
Frame2 = 00000000

UpdateFreq = 180000

UVTran = "Minimal" : "弱い", "Low" : "弱い", "Moderate" : "ふつう", "Very High" : "とても強い" , "High" : "強い", "Extreme" : "非常に強い"
UVTran2 = "1" : "Nia-san1", "2" : "Nia-san2", "3" : "Nia-san3", "0" : "Nia-san1"
UVTran3 = "1" : "私はアールグレイティー派だ", "2" : "ちょっと紫外線が強いかな", "3" : "うぐっ・・・！", "0" : "私はアールグレイティー派だ"

; 書式設定の定義です。
[FontString]
FontSize = 10
StringStyle = Normal
StringAlign = Left
FontFace = Segoe UI
FontColor = #Foreground#
StringEffect = Shadow
FontEffectColor = 646464FF
AntiAlias = 1
