[Variables]

; カラーの定義です。
Background = 000000C0
Foreground = F0FFFFFF
Frame = E3A14BFF
Frame2 = 00000000

; 書式設定の定義です。
[FontVal]
FontSize = 14
StringStyle = Normal
StringAlign = Center
FontFace = Meiryo UI
FontColor = #Foreground#
StringEffect = Shadow
FontEffectColor = 646464FF
AntiAlias = 1

[FontLabel]
FontSize = 8
StringStyle = Normal
StringAlign = Center
FontFace = Segoe UI
FontColor = #Foreground#
StringEffect = Shadow
FontEffectColor = 646464FF
AntiAlias = 1

