[Variables]
;--- クエリちゃん ストレージメーター用 ---

; ディスクドライブを指定します。（最大4つまで指定することができます。）
; "ドライブレター:"
; Strage1.ini、Strage2.ini、Strage3.ini、Strage4.iniで使用します。
disk1 = C:
; Strage2.ini、Strage3.ini、Strage4.iniで使用します。
disk2 = D:
; Strage3.ini、Strage4.iniで使用します。
disk3 = E:
; Strage4.iniで使用します。
disk4 = F:


;--- 東北ずん子ちゃん RSSリーダー用 ---
; RSSのURIを指定します。
ZNDRSSURI = http://tohokuzunko.blog.fc2.com/?xml

;--- ハッカちゃん RSSリーダー用 ---
; RSSのURIを指定します。
HKDRSSURI = http://blog.hackadoll.com/rss

; RSS1.0形式（ルートノードがRDF）
; 東北ずん子　オフィシャルブログ：http://tohokuzunko.blog.fc2.com/?xml

; RSS2.0（ルートノードがRSS）
; プログラミング生放送　　　　　　　　　　　　　：http://pronama.azurewebsites.net/feed/
; クラウディア・窓辺 (@Claudia_Azure) のツイート：http://sxp.microsoft.com/feeds/msdntn/claudia_azure_twitter/
; ユニティちゃんのブログ　　　　　　　　　　　　：http://unity-chan.com/blog/?feed=rss2
; ハッカドール(Hackadoll) 公式運営ブログ　　　　：http://blog.hackadoll.com/rss
; Myoga-TN.net　　　　　　　　　　　　　　　　　：http://myoga-tn.expressweb.jp/feed/


;--- Myoga ウェザーメーター用 ---

; Locationにはロケーションコードを指定します。
; Weather1.iniで使用します。
Location = JAXX0085
; Weather2.iniで使用します。
Location2 = JAXX0057
; Weather3.iniで使用します。
Location3 = JAXX0071

; 例
; 札幌　 : JAXX0078
; 仙台　 : JAXX0104
; 東京　 : JAXX0085
; 名古屋 : JAXX0057
; 新潟　 : JAXX0061
; 金沢　 : JAXX0030
; 大阪　 : JAXX0071
; 広島　 : JAXX0018
; 高知　 : JAXX0238
; 福岡　 : JAXX0009
; 那覇　 : JAXX0058

; 詳細はマニュアルを参照してください。

