[Variables]
;--- クエリちゃん ストレージメーター用 ---

; ディスクドライブを指定します。（最大4つまで指定することができます。）
; "ドライブレター:"
; Strage1.ini、Strage2.ini、Strage3.ini、Strage4.iniで使用します。
disk1 =C:
; Strage2.ini、Strage3.ini、Strage4.iniで使用します。
disk2 =D:
; Strage3.ini、Strage4.iniで使用します。
disk3 =E:
; Strage4.iniで使用します。
disk4 =F:


;--- 東北ずん子ちゃん RSSリーダー用 ---
; RSSのURIを指定します。
ZNDRSSURI = http://pronama.azurewebsites.net/feed/

;--- ハッカちゃん RSSリーダー用 ---
; RSSのURIを指定します。
HKDRSSURI = http://myoga-tn.expressweb.jp/feed/

; RSS1.0形式（ルートノードがRDF）
; -

; RSS2.0（ルートノードがRSS）
; プログラミング生放送　　　　　　　　　　　　　：http://pronama.azurewebsites.net/feed/
; Choronoir.net（旧Myoga-TN.net） 　　　　　　　：http://myoga-tn.expressweb.jp/feed/


;--- Myogaさん ウェザーメーター、Niaさん、UVチェッカー用 ---

; Locationにはロケーションコードを指定します。
; Weather1.iniで使用します。
Location =JAXX0085
; Weather2.iniで使用します。
Location2 =JAXX0036
; Weather3.iniで使用します。
Location3 =JAXX0048

; 例
; 札幌　 : JAXX0078
; 仙台　 : JAXX0104
; 東京　 : JAXX0085
; 名古屋 : JAXX0057
; 新潟　 : JAXX0061
; 金沢　 : JAXX0030
; 大阪　 : JAXX0071
; 広島　 : JAXX0018
; 高知　 : JAXX0238
; 福岡　 : JAXX0009
; 那覇　 : JAXX0058

; 詳細はマニュアルを参照してください。

