[Variables]
;--- クエリちゃん ストレージメーター用 ---

; ディスクドライブを指定します。
; "ドライブレター:"
disk1 = C:
disk2 = D:


;--- 東北ずん子ちゃん RSSフィーダー用 ---
; RSSのURIを指定します。（※RSS1.0形式（ルートノードがRDF）に対応しています）
RDFURI = http://tohokuzunko.blog.fc2.com/?xml
; 東北ずん子　オフィシャルブログ：http://tohokuzunko.blog.fc2.com/?xml


;--- ハッカちゃん RSSフィーダー用 ---
; RSSのURIを指定します。（※RSS2.0形式（ルートノードがRSS）に対応しています）
RSSURI = http://blog.hackadoll.com/rss
; プログラミング生放送　　　　　　　　　　　　　：http://pronama.azurewebsites.net/feed/
; クラウディア・窓辺 (@Claudia_Azure) のツイート：http://sxp.microsoft.com/feeds/msdntn/claudia_azure_twitter/
; ユニティちゃんのブログ　　　　　　　　　　　　：http://unity-chan.com/blog/?feed=rss2
; ハッカドール(Hackadoll) 公式運営ブログ　　　　：http://blog.hackadoll.com/rss
; Myoga-TN.net　　　　　　　　　　　　　　　　　：http://myoga-tn.expressweb.jp/feed/


;--- Myoga ウェザーメーター用 ---

; Locationにはロケーションコードを指定します。
Location = JAXX0565
; 例
; 札幌　 : JAXX0078
; 仙台　 : JAXX0104
; 東京　 : JAXX0085
; 名古屋 : JAXX0057
; 新潟　 : JAXX0061
; 金沢　 : JAXX0030
; 大阪　 : JAXX0071
; 広島　 : JAXX0018
; 高知　 : JAXX0238
; 福岡　 : JAXX0009
; 那覇　 : JAXX0058

; 詳細はマニュアルを参照してください。

